### ISSUE TITLE
Hash(es) leaked! 

### ISSUE THREAD

**Issue by hohky** [parthpanchal3399/Quiz-Application-With-dB-Connectivity-on-Python-Tkinter-#1]
In file **QuizDatabase.sql**, 2 hashes leaked!

Security Vulnerability ->  ***Password in Configuration File*** / Information Disclosure

**Comment by parthpanchal3399** [comment]
Great observation! However the accounts that are made are test accounts not real users. 

Anyways thanks for pointing out! 👍

**Comment by hohky** [comment]
Ok 😅
