### ISSUE TITLE
authentication problem

### ISSUE THREAD

**Issue by ApoorvSr** [parthpanchal3399/Quiz-Application-With-dB-Connectivity-on-Python-Tkinter-#3]
"Authentication plugin '{0}' is not supported".format(plugin_name))
mysql.connector.errors.NotSupportedError: Authentication plugin 'caching_sha2_password' is not supported       
PS C:\Users\apoor\OneDrive\Desktop\Quiz-Application-With-dB-Connectivity-on-Python-Tkinter--master\Quiz-Application-With-dB-Connectivity-on-Python-Tkinter--master>

**Comment by parthpanchal3399** [comment]
Hi @ApoorvSr ,
Try following this: https://lindevs.com/change-default-authentication-plugin-in-mysql
